(() => {
  const $ = s => document.querySelector(s);
  const source = $('#sourceText'), wordCount = $('#wordCount'), readTime = $('#readTime'), voiceSelect = $('#voice'), speed = $('#speed'), speedValue = $('#speedValue'), status = $('#status'), progressBar = $('#progressBar'), currentCard = $('#currentCard'), nowReading = $('#nowReading'), chunkTag = $('#chunkTag'), summaryCard = $('#summaryCard'), summaryText = $('#summaryText'), installBtn = $('#installBtn');
  let voices=[], chunks=[], currentIndex=0, playing=false, stopped=true, currentUtterance=null, deferredPrompt=null;
  const countWords=t=>(t.trim().match(/\S+/g)||[]).length;
  const getMode=()=>document.querySelector('input[name="mode"]:checked').value;
  function updateMeta(){const wc=countWords(source.value);wordCount.textContent=`${wc} words`;const mins=wc/(150*Number(speed.value||1));readTime.textContent=`~${wc?Math.max(1,Math.round(mins)):0} min at ${Number(speed.value).toFixed(1)}×`;}
  source.addEventListener('input',updateMeta); speed.addEventListener('input',()=>{speedValue.textContent=Number(speed.value).toFixed(1)+'×';updateMeta();});
  function loadVoices(){if(!('speechSynthesis' in window)){voiceSelect.innerHTML='<option>Not supported by this browser</option>';$('#playBtn').disabled=true;status.textContent='Your browser does not expose text-to-speech. Try Chrome or Edge on the hosted site.';return;}voices=speechSynthesis.getVoices();voiceSelect.innerHTML='';if(!voices.length){voiceSelect.innerHTML='<option>Default device voice</option>';return;}const order=[...voices].sort((a,b)=>{const ai=/en[-_]IN/i.test(a.lang)?0:/^en/i.test(a.lang)?1:2;const bi=/en[-_]IN/i.test(b.lang)?0:/^en/i.test(b.lang)?1:2;return ai-bi||a.name.localeCompare(b.name);});order.forEach(v=>{const o=document.createElement('option');o.value=voices.indexOf(v);o.textContent=`${v.name} — ${v.lang}${v.default?' (default)':''}`;voiceSelect.appendChild(o);});}
  loadVoices(); if('speechSynthesis' in window)speechSynthesis.onvoiceschanged=loadVoices;
  const financeKeywords=['revenue','sales','ebitda','ebit','margin','profit','pat','eps','growth','cagr','guidance','capacity','utilisation','utilization','order book','debt','net debt','cash','capex','market share','penetration','competition','risk','outlook','target','launch','export','acquisition','stake','crore','cr','lakh','million','billion','gw','mw','fy','yoy','qoq','ipo','ev','cng','data centre','data center','ai','plant','expansion','pricing','volume','demand','management','working capital','free cash flow','return on capital','roce','roe','promoter','pledge','valuation','pe','p/e','catalyst','headwind','tailwind'];
  function scoreLine(line){let s=0;const low=line.toLowerCase();financeKeywords.forEach(k=>{if(low.includes(k))s+=2;});if(/[₹$€£]\s?\d/.test(line))s+=2;if(/\b\d+(\.\d+)?\s?%/.test(line))s+=2;if(/\b\d[\d,.]*\s?(cr|crore|lakh|million|billion|mw|gw|mt)\b/i.test(line))s+=2;if(/\b(fy\d{2}|q[1-4]|h[12])\b/i.test(line))s+=1;if(/risk|concern|headwind|competition|decline|fraud|overhang|pressure/i.test(line))s+=2;if(/growth|expansion|guidance|target|capacity|launch|order book|margin/i.test(line))s+=2;return s;}
  function isHeading(line){const t=line.replace(/^[-*#\s]+/,'').trim();return t.length>2&&t.length<90&&(/^\d+[\.\)]\s+/.test(t)||/industries|motor|technologies|max|suzuki|limited|ltd|bank|finance|energy/i.test(t))&&!/[.!?]$/.test(t);}
  function smartSummarize(text){const clean=text.replace(/\r/g,'').replace(/[•●▪◦]/g,'-');const rawLines=clean.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(rawLines.length<=8)return clean.trim();const output=[];let section=[],heading='';function flush(){if(!section.length)return;const scored=section.map((line,idx)=>({line,idx,score:scoreLine(line)}));const keepCount=Math.min(7,Math.max(3,Math.ceil(section.length*.42)));const selected=scored.sort((a,b)=>b.score-a.score||a.idx-b.idx).slice(0,keepCount).sort((a,b)=>a.idx-b.idx).map(x=>x.line);if(heading)output.push('\n'+heading);selected.forEach(x=>output.push(x.replace(/^[-*#]+\s*/,'').trim()));section=[];}for(const line of rawLines){if(isHeading(line)){flush();heading=line.replace(/^[-*#]+\s*/,'').trim();}else section.push(line);}flush();let result=output.join('\n').replace(/\n{3,}/g,'\n\n').trim();const targetMax=Math.max(280,Math.round(countWords(clean)*.52));const arr=result.split(/\s+/);if(arr.length>targetMax)result=arr.slice(0,targetMax).join(' ')+'…';return result||clean.trim();}
  function speechFriendly(text){return text.replace(/₹\s*([\d,.]+)/g,'$1 rupees ').replace(/\bCr\b/gi,'crore').replace(/\bFY(\d{2})\b/gi,'financial year $1').replace(/\bYoY\b/gi,'year on year').replace(/\bQoQ\b/gi,'quarter on quarter').replace(/\bEBITDA\b/g,'E B I T D A').replace(/\bEBIT\b/g,'E B I T').replace(/\bCAGR\b/g,'C A G R').replace(/\bROCE\b/g,'R O C E').replace(/\bROE\b/g,'R O E').replace(/\bEV\b/g,'E V').replace(/\bAI\b/g,'A I').replace(/\bMW\b/g,'megawatts').replace(/\bGW\b/g,'gigawatts').replace(/\bMT\b/g,'metric tonnes').replace(/~/g,'approximately ').replace(/%/g,' percent ').replace(/\//g,' per ');}
  function makeChunks(text,max=850){const normalized=text.replace(/\n+/g,'. ').replace(/\s+/g,' ').trim();const sentences=normalized.split(/(?<=[.!?])\s+/);const out=[];let cur='';for(const s of sentences){if((cur+' '+s).length>max&&cur){out.push(cur.trim());cur=s;}else cur+=(cur?' ':'')+s;}if(cur.trim())out.push(cur.trim());return out;}
  function updateProgress(){const pct=chunks.length?(currentIndex/chunks.length)*100:0;progressBar.style.width=`${Math.min(100,pct)}%`;}
  function stopSpeech(msg='Stopped.'){stopped=true;playing=false;if('speechSynthesis' in window)speechSynthesis.cancel();currentUtterance=null;status.textContent=msg;updateProgress();}
  function speakCurrent(){if(stopped||currentIndex>=chunks.length){if(currentIndex>=chunks.length&&chunks.length){progressBar.style.width='100%';status.textContent='Finished reading.';}playing=false;return;}const text=chunks[currentIndex];const u=new SpeechSynthesisUtterance(text);currentUtterance=u;const vi=Number(voiceSelect.value);if(Number.isInteger(vi)&&voices[vi])u.voice=voices[vi];u.rate=Number(speed.value);u.pitch=1;nowReading.textContent=text;chunkTag.textContent=`${currentIndex+1} / ${chunks.length}`;currentCard.classList.remove('hidden');u.onstart=()=>{playing=true;status.textContent=`Reading ${getMode()==='smart'?'Smart Mode':'Word-for-Word'}…`;updateProgress();};u.onend=()=>{if(stopped)return;currentIndex++;updateProgress();setTimeout(speakCurrent,80);};u.onerror=e=>{if(!stopped)status.textContent=`Speech error: ${e.error||'unknown error'}`;};speechSynthesis.speak(u);}
  function prepareAndPlay(){const raw=source.value.trim();if(!raw){status.textContent='Paste an article first.';source.focus();return;}if(!('speechSynthesis' in window)){status.textContent='Text-to-speech is not available in this browser.';return;}if(speechSynthesis.paused){speechSynthesis.resume();status.textContent='Resumed.';return;}speechSynthesis.cancel();stopped=false;playing=true;currentIndex=0;const prepared=getMode()==='smart'?smartSummarize(raw):raw;if(getMode()==='smart'){summaryText.textContent=prepared;summaryCard.classList.remove('hidden');}else summaryCard.classList.add('hidden');chunks=makeChunks(speechFriendly(prepared));updateProgress();speakCurrent();}
  $('#playBtn').addEventListener('click',prepareAndPlay);$('#pauseBtn').addEventListener('click',()=>{if(!('speechSynthesis' in window))return;if(speechSynthesis.speaking&&!speechSynthesis.paused){speechSynthesis.pause();status.textContent='Paused.';}else if(speechSynthesis.paused){speechSynthesis.resume();status.textContent='Resumed.';}});$('#stopBtn').addEventListener('click',()=>stopSpeech());
  $('#previewBtn').addEventListener('click',()=>{const raw=source.value.trim();if(!raw){status.textContent='Paste an article first.';return;}const s=smartSummarize(raw);summaryText.textContent=s;summaryCard.classList.remove('hidden');status.textContent=`Smart preview created locally: ${countWords(s)} words.`;});
  $('#clearBtn').addEventListener('click',()=>{stopSpeech('Cleared.');source.value='';summaryText.textContent='';summaryCard.classList.add('hidden');currentCard.classList.add('hidden');chunks=[];currentIndex=0;progressBar.style.width='0';updateMeta();});
  function estimateChunkJump(seconds){const wps=2.5*Number(speed.value),targetWords=Math.max(1,Math.round(seconds*wps));let words=0,steps=0;for(let i=currentIndex;i<chunks.length;i++){words+=countWords(chunks[i]);steps++;if(words>=targetWords)break;}return Math.max(1,steps);}
  $('#forwardBtn').addEventListener('click',()=>{if(!chunks.length)return;currentIndex=Math.min(chunks.length-1,currentIndex+estimateChunkJump(15));if('speechSynthesis' in window)speechSynthesis.cancel();stopped=false;speakCurrent();});$('#backBtn').addEventListener('click',()=>{if(!chunks.length)return;currentIndex=Math.max(0,currentIndex-estimateChunkJump(15));if('speechSynthesis' in window)speechSynthesis.cancel();stopped=false;speakCurrent();});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden');});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden');});if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});updateMeta();
})();