(()=>{
const $=s=>document.querySelector(s),source=$('#sourceText'),voiceSelect=$('#voice'),speed=$('#speed'),status=$('#status'),summaryCard=$('#summaryCard'),summaryText=$('#summaryText'),currentCard=$('#currentCard'),nowReading=$('#nowReading'),chunkTag=$('#chunkTag'),bar=$('#progressBar');
let voices=[],chunks=[],idx=0,stopped=true,current=null,lastVoiceKey=localStorage.getItem('readerVoice')||'',generation=0;
const words=t=>(t.trim().match(/\S+/g)||[]).length,mode=()=>document.querySelector('input[name=mode]:checked').value;
function meta(){let w=words(source.value),m=w/(150*Number(speed.value));$('#wordCount').textContent=w+' words';$('#readTime').textContent='~'+(w?Math.max(1,Math.round(m)):0)+' min at '+Number(speed.value).toFixed(1)+'×';$('#speedValue').textContent=Number(speed.value).toFixed(1)+'×'}source.oninput=meta;speed.oninput=meta;
function key(v){return [v.name,v.lang,v.voiceURI].join('|||')}
function loadVoices(){if(!window.speechSynthesis){voiceSelect.innerHTML='<option>Speech unavailable</option>';status.textContent='This browser does not provide device speech.';return}const fresh=speechSynthesis.getVoices();if(!fresh.length)return;voices=fresh;const english=voices.filter(v=>/^en/i.test(v.lang));const list=(english.length?english:voices).sort((a,b)=>{let ar=/en[-_]IN/i.test(a.lang)?0:/en[-_](GB|US|AU)/i.test(a.lang)?1:2,br=/en[-_]IN/i.test(b.lang)?0:/en[-_](GB|US|AU)/i.test(b.lang)?1:2;return ar-br||a.name.localeCompare(b.name)});voiceSelect.innerHTML='';list.forEach(v=>{let o=document.createElement('option');o.value=key(v);o.textContent=v.name+' — '+v.lang+(v.localService?' • device':'');voiceSelect.appendChild(o)});let chosen=list.find(v=>key(v)===lastVoiceKey)||list.find(v=>/en[-_]IN/i.test(v.lang))||list[0];voiceSelect.value=key(chosen);lastVoiceKey=voiceSelect.value;localStorage.setItem('readerVoice',lastVoiceKey);$('#voiceHint').textContent=`${list.length} English voice${list.length===1?'':'s'} found on this device. Selected: ${chosen.name}.`}
loadVoices();speechSynthesis.onvoiceschanged=loadVoices;setTimeout(loadVoices,250);setTimeout(loadVoices,1000);
function selectedVoice(){return voices.find(v=>key(v)===voiceSelect.value)||voices.find(v=>/en[-_]IN/i.test(v.lang))||voices[0]}
function sayTest(){if(!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance('This is the selected voice. Revenue grew twenty five percent, while EBITDA margin improved to twelve percent.');u.voice=selectedVoice();u.rate=Number(speed.value);u.onstart=()=>status.textContent='Testing: '+(u.voice?.name||'device voice');u.onend=()=>status.textContent='Voice test finished. If you like it, press Start Listening.';speechSynthesis.speak(u)}$('#testVoiceBtn').onclick=sayTest;
voiceSelect.onchange=()=>{lastVoiceKey=voiceSelect.value;localStorage.setItem('readerVoice',lastVoiceKey);let v=selectedVoice();status.textContent='Voice changed to '+(v?.name||'selected voice')+'.';if(!stopped&&chunks.length){generation++;speechSynthesis.cancel();setTimeout(()=>speak(idx),100)}};
const kw=['revenue','sales','ebitda','margin','profit','pat','eps','growth','cagr','guidance','capacity','utilisation','utilization','order book','debt','cash','capex','market share','penetration','competition','risk','outlook','target','launch','export','acquisition','stake','crore','lakh','million','billion','plant','expansion','pricing','volume','demand','management','working capital','free cash flow','roce','roe','promoter','valuation','catalyst','headwind','tailwind'];
function score(s){let l=s.toLowerCase(),n=0;kw.forEach(k=>{if(l.includes(k))n+=2});if(/[₹$€£]\s?\d/.test(s))n+=2;if(/\d+(\.\d+)?\s?%/.test(s))n+=2;if(/\b(fy\d{2}|q[1-4]|h[12])\b/i.test(s))n++;if(/risk|pressure|decline|competition|fraud|overhang|concern/i.test(s))n+=3;return n}
function smart(text){let cleaned=text.replace(/\r/g,' ').replace(/[•●▪◦]/g,'. ').replace(/\n+/g,'. ').replace(/\s+/g,' ').trim();let ss=cleaned.split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(x=>x.length>25);if(ss.length<7)return cleaned;let chosen=ss.map((s,i)=>({s,i,n:score(s)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||a.i-b.i).slice(0,Math.max(6,Math.min(28,Math.ceil(ss.length*.38)))).sort((a,b)=>a.i-b.i);let out=[],last=-99;chosen.forEach(x=>{if(x.i-last>3&&out.length)out.push('Next important point.');out.push(x.s);last=x.i});return 'Here are the key points from this research. '+out.join(' ')+' That is the end of the key points.'}
function friendly(t){return t.replace(/₹\s*([\d,.]+)/g,'$1 rupees ').replace(/\bCr\b/gi,'crore').replace(/\bFY(\d{2})\b/gi,'financial year $1').replace(/\bYoY\b/gi,'year on year').replace(/\bQoQ\b/gi,'quarter on quarter').replace(/\bEBITDA\b/g,'E B I T D A').replace(/\bCAGR\b/g,'C A G R').replace(/\bROCE\b/g,'R O C E').replace(/\bROE\b/g,'R O E').replace(/\bMW\b/g,'megawatts').replace(/\bGW\b/g,'gigawatts').replace(/~/g,'approximately ').replace(/%/g,' percent ')}
function split(t,max=420){let ss=t.replace(/\n+/g,'. ').replace(/\s+/g,' ').split(/(?<=[.!?])\s+/),a=[],c='';ss.forEach(s=>{if((c+' '+s).length>max&&c){a.push(c.trim());c=s}else c+=(c?' ':'')+s});if(c.trim())a.push(c.trim());return a}
function progress(){bar.style.width=(chunks.length?Math.min(100,(idx/chunks.length)*100):0)+'%'}
function speak(i){if(stopped||i>=chunks.length){if(i>=chunks.length&&chunks.length){bar.style.width='100%';status.textContent='Finished.'}return}idx=i;let myGen=generation,u=new SpeechSynthesisUtterance(chunks[idx]),v=selectedVoice();current=u;if(v)u.voice=v;u.rate=Number(speed.value);u.pitch=1;nowReading.textContent=chunks[idx];chunkTag.textContent=(idx+1)+' / '+chunks.length;currentCard.classList.remove('hidden');u.onstart=()=>{status.textContent='Playing with '+(v?.name||'device voice')+' • '+Number(speed.value).toFixed(1)+'×';progress()};u.onend=()=>{if(stopped||myGen!==generation)return;idx++;progress();setTimeout(()=>speak(idx),70)};u.onerror=e=>{if(!stopped&&e.error!=='canceled'&&e.error!=='interrupted')status.textContent='Speech problem: '+e.error};speechSynthesis.speak(u)}
function start(){let raw=source.value.trim();if(!raw){status.textContent='Paste an article first.';source.focus();return}if(!speechSynthesis){status.textContent='Speech is unavailable in this browser.';return}if(speechSynthesis.paused){speechSynthesis.resume();status.textContent='Resumed.';return}generation++;speechSynthesis.cancel();stopped=false;idx=0;let prepared=mode()==='smart'?smart(raw):raw;if(mode()==='smart'){summaryText.textContent=prepared;summaryCard.classList.remove('hidden')}else summaryCard.classList.add('hidden');chunks=split(friendly(prepared));progress();setTimeout(()=>speak(0),100)}
$('#playBtn').onclick=start;$('#pauseBtn').onclick=()=>{if(speechSynthesis.paused){speechSynthesis.resume();status.textContent='Resumed.'}else if(speechSynthesis.speaking){speechSynthesis.pause();status.textContent='Paused.'}};$('#stopBtn').onclick=()=>{stopped=true;generation++;speechSynthesis.cancel();status.textContent='Stopped.'};$('#forwardBtn').onclick=()=>{if(!chunks.length)return;generation++;speechSynthesis.cancel();stopped=false;idx=Math.min(chunks.length-1,idx+1);setTimeout(()=>speak(idx),80)};$('#backBtn').onclick=()=>{if(!chunks.length)return;generation++;speechSynthesis.cancel();stopped=false;idx=Math.max(0,idx-1);setTimeout(()=>speak(idx),80)};
speed.onchange=()=>{meta();if(!stopped&&chunks.length){generation++;speechSynthesis.cancel();setTimeout(()=>speak(idx),80)}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});meta();
})();